#ifndef TRITONNPU_OPS
#define TRITONNPU_OPS

include "triton/Dialect/TritonNPU/IR/TritonNPUDialect.td"
include "triton/Dialect/TritonNPU/IR/TritonNPUTypes.td"
include "triton/Dialect/TritonNPU/IR/TritonNPUAttrDefs.td"
include "mlir/Dialect/Arith/IR/ArithBase.td"
include "triton/Dialect/Triton/IR/TritonTypes.td"
include "triton/Dialect/Triton/IR/TritonAttrDefs.td"
include "mlir/IR/OpBase.td"

#endif
